### ISSUE TITLE
Symbolic Math Toolbox needed

### ISSUE THREAD

**Issue by ahbarnett** [bobbielf2/ZetaTrap2D#1]
Hi Bobbie,
You will want to list the requirements (matlab version + toolboxes) needed. Looks like you call vpa in the crucial 3-line weight gen func, for non-standard orders. I can't run it on laptop since don't have that toolbox... test_sto2d_bie works great, but test_helm2d_bie needs vpa.
Cheers, Alex

**Comment by bobbielf2** [comment]
Hi Alex, 
This should be fixed now. 
Thanks,
Bobbie
